### ISSUE TITLE
Fill option in Stack and Queue

### ISSUE THREAD

**Issue by jayjoshi64** [ikushum/Lets-do-DataStructure-and-Algorithm#2]
You can initialize a keyword parameter in each class to fill the stack from a list.!
it will be easier to fill a stack or queue using a list.
it's just an idea to expand your project.

you can try like this:

     __init__(self,size,fill=None):

in every class.

here is the sample for the stack:

	def __init__(self,size,fill=None):
		self.size = size
		self.top = -1
		self.array = [None] * self.size

        if fill:
            self.array[:len(fill)] = list(fill)

**Comment by jayjoshi64** [comment]
https://github.com/ikushum/Lets-do-DataStructure-and-Algorithm/blob/df5b3f7598eac57d51f21d2790eac677e028540d/Data_Structures_(basic)/singly_linked_list.py#L3

is not safe because if the `data` is changed outside the class, there will also be change in the class `data`.
it is because it is referenced to the data. not actually copied.

**Comment by ikushum** [comment]
Hey @jayjoshi64! Thanks for reaching out :+1: 
About first comment, definitely, that's an awesome way to fill out elements on our data structures. But for now, I think I should stick with a basic implementation.
About second comment, what solution would you suggest for this issue ?

**Comment by jayjoshi64** [comment]
sorry for the misunderstanding lad.
i though `data` is a list. but now i understand it is not.
so data will be copied instead of referencing.
don't worry about that.

**Comment by jayjoshi64** [comment]
Although there is another problem I see.
when you specify `data=None` in argument, that is a keyword argument.
keyword arguments are optional, but if you have to give argument you have to give it like `Node(data=dataobj)` .
and this will not work `Node(dataobj)`.

here is where i see it:
https://github.com/ikushum/Lets-do-DataStructure-and-Algorithm/blob/df5b3f7598eac57d51f21d2790eac677e028540d/Data_Structures_(basic)/singly_linked_list.py#L11

it should be like:

     newNode = Node(data=data)

**Comment by ikushum** [comment]
Thanks for the comment. I defined a regular argument (instead of keyword argument) in the constructor of Node class and to balance the change, I passed `None` as an argument while creating `head` inside the constructor of Linked List class.

**Comment by jayjoshi64** [comment]
Okay, That solves the Problem.  :)
keep coding..
