### ISSUE TITLE
Few concept guide

### ISSUE THREAD

**Issue by jayjoshi64** [ikushum/Lets-do-DataStructure-and-Algorithm#3]
It is good that you are implementing important data structures and improving in data structure concepts and in python.

Its really nice that you use Object oriented implementation for each data structure and it is best way to do so. I think you need to understand few tips.

You created Binary Search Tree. And you implemented Insert, Search, Delete methods in `Node` Object. which i found not the best way to do it.

think, 
who has every  node.?
"Tree"
To whom you are asking to insert a Node.?
"Tree"
To whom should you ask to get a Node.?
"Tree"

If Tree has each and every node in it... Why you are implementing the method in 'Node' object.?

Think like they are small human. with little brain which you are creating.
what are each of their purpose of life.?
Node : To store data and 2 links. Where you put node it will not ask question or do anything. it will adjust itself and do nothing. Node is for storage purpose only.
Tree: To maintain tree of nodes. to "maintain" it should have method like insert, search, and delete.!

( if you open a box of chocolate you do not ask first chocolate to find the "perk" named chocolate from whole box. You find it yourself.! it is same for the Tree.)

If a new person runs your code. He will definitely do `Tree.insert( NewData )` instead of `node.insert`. 

I hope you get my point.

If you are still confused how to use object and methods in objects.
think like each have their jobs to do. Which job should be best for the object.?
this thinking would give you better practice.

I made my logic from making many games where each object have task and animation to perform. 
I hope it helps

**Comment by ikushum** [comment]
Thanks for the explanation :+1:  I re-factored the code considering every node in the tree has a right and left subtree( including subtrees having single node ) and every tree (including subtree) has a parent node.

**Comment by jayjoshi64** [comment]
Very good :)
